name: PR Test

on:
  pull_request:

jobs:
  check-jira-base-url:
    runs-on: ubuntu-latest
    steps:
      - name: Check JIRA_BASE_URL secret
        run: |
          if [ -z "${{ secrets.SECRETS_TEST }}" ]; then
            echo "${{ secrets.SECRETS_TEST }}"
          else
            echo "fuga"
          fi
